apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"     #ClusterIssuer for staging environment 
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - example.example.com
    secretName: staging-www-tls # TLS secret for staging
  rules:
  - host: example.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-app
            port:
              number: 80
