apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging  # clusterIssuer for staging environment
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.goodnesseboh.engineer
    secretName: staging-app-tls  # TLS secret for staging
  rules:
  - host: www.goodnesseboh.engineer
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-app
            port:
              number: 80
